ShopKub/ShopKub/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls")),
    path("items/", include("item.urls")),
    path('admin/', admin.site.urls),
    path('dashboard/', include("dashboard.urls")),
    path('inbox/', include("conversation.urls")),
    path('userprofile/', include("userprofile.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ShopKub/conversation/urls.py
from django.urls import path

from . import views

app_name = "conversation"

urlpatterns = [
    path("", views.inbox, name="inbox"),
    path("<int:pk>/", views.detail, name="detail"),
    path("new/<int:item_pk>/", views.new_conversation, name="new")
]

ShopKub/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm
app_name = "core"

urlpatterns = [
    path('', views.index, name="index"),
    path("contact/", views.contact, name="contact"),
    path("signup/", views.signup, name="signup"),
    path("login/", auth_views.LoginView.as_view(authentication_form=LoginForm, 
                                                template_name='core/login.html'), name="login"),
    path("signout/", views.sign_out, name="signout"),
]

ShopKub/dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path('', views.index, name="index")
]

ShopKub/item/urls.py
from django.urls import path

from . import views

app_name ="item"

urlpatterns = [
    path('', views.items, name="items"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/edit/", views.edit, name="edit"),
    path("new/", views.new, name="new")
]

ShopKub/userprofile/urls.py
from django.urls import path

from . import views

app_name ="userprofile"

urlpatterns = [
    path("detail/", views.detail, name="detail")
]

ShopKub/core/models.py
from django.db import models

ShopKub/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Your usernmae' ,
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Your password' ,
        'class':'w-full py-4 px-6 rounded-xl'
    }))

    
class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Your username' ,
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Your email' ,
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Your password' ,
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Repeat password' ,
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Your First Name' ,
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Your Last Name' ,
        'class':'w-full py-4 px-6 rounded-xl'
    }))

ShopKub/core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from userprofile.forms import UserProfileForm

def index(request):
    items = Item.objects.filter(is_sold=False)[:6]
    categories = Category.objects.all()

    return render(request, "core/index.html", {
        "categories": categories,
        "items": items
    })

def contact(request):
    return render(request, "core/contact.html")

def signup(request):
    if request.method == "POST":
        core_form = SignupForm(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)
        if core_form.is_valid() and profile_form.is_valid():
            user = core_form.save()
            profile_form.instance.user = user
            profile_form.save()
        return redirect("/login/")
    else:
        core_form = SignupForm()
        profile_form = UserProfileForm()
    return render(request, "core/signup.html", {"core_form":core_form,"profile_form":profile_form})

@login_required
def sign_out(request):
    logout(request)
    return redirect('/')

ShopKub/core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, intial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title %}{% endblock %} | SHOPKUB</title>
    </head>
    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
           <a href="/" class="text-xl font-semibold"> SHOPKUB</a>

           <div class="space-x-6">
                <a href="{% url 'item:new' %}" class="text-lg front-semibold hover:text-gray-500"> New Item</a>
                <a href="{% url 'item:items' %}" class="text-lg front-semibold hover:text-gray-500"> Browse</a>

                {% if request.user.is_authenticated %}
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"> Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700"> Dashboard</a>
                    <a href="{% url 'core:signout' %}" class="px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700"> Log out</a>
                    <a href="{% url 'userprofile:detail' %}" class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700"> Profile</a>
                {% else %}
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"> Login</a>
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700"> Sign up</a>
                {% endif %}
                
           </div>

        </nav>
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>
        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">
                    About
                </h3>
                <p class="text-lg text-gray-500">
                    This website created in tutorial class by Achitaphon Pratanvanich
                </p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul>
                    <li> <a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li> <a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li> <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                    <li> <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

ShopKub/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}contact{% endblock %}

{% block content %}
    <h1>The Contact Page</h1>
{% endblock %}

ShopKub/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest Items</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    <img src="{{item.image.url}}" class="rounded-xl object-cover h-48">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl"> {{item.name}} </h2>
                    <p class="text-gray-500"> Price: {{item.price}} </p>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <a href="#">
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl"> {{category.name}} </h2>
                    <p class="text-gray-500"> {{category.items.count}} items</p>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

ShopKub/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="w=1/2 my-6 mx-auto bg-gray-100 rounded-xl p-6">
    <h1 class="mb-6 text-3xl">Login</h1>
    <form method="post", action=".">
        {% csrf_token %}
        
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{form.username}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{form.password}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}

                {{ form.non_field_errors}}
            </div>
        {% endif %}
    <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>

{% endblock %}

ShopKub/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Signup{% endblock %}

{% block content %}

<div class="w=1/2 my-6 mx-auto bg-gray-100 rounded-xl p-6">
    <h1 class="mb-6 text-3xl">Sign Up</h1>
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{core_form.username}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{core_form.email}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{core_form.password1}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{core_form.password2}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Firstname</label><br>
            {{core_form.first_name}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Lastname</label><br>
            {{core_form.last_name}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Address</label><br>
            {{profile_form.address}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Telephone number</label><br>
            {{profile_form.tel_number}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Profile picture</label><br>
            {{profile_form.profile_picture}}
        </div>

        {% if core_form.errors or core_form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in core_form %}
                    {{field.errors}}
                {% endfor %}

                {{ core_form.non_field_errors}}
            </div>
        {% endif %}
        {% if profile_form.errors or profile_form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in profile_form %}
                    {{field.errors}}
                {% endfor %}

                {{ profile_form.non_field_errors}}
            </div>
        {% endif %}
    <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>

{% endblock %}